<a href="https://colab.research.google.com/github/agapitouTheou/Predictive-maintenance-model-/blob/main/2_project_numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# NUMPY BASICS
# NumPy = Numerical Python (work with arrays of sensor data)

import numpy as np

print("="*50)
print("NUMPY: FOUNDATION FOR ML ENGINEERS")
print("="*50)

# ===== 1. CREATE ARRAYS (Like sensor readings over time) =====
print("\n1. CREATING ARRAYS")

# Array of temperature readings
temps = np.array([85.2, 86.1, 87.3, 88.5, 89.2, 90.1, 91.3])
print(f"Temperature array: {temps}")
print(f"Array shape (how many readings): {temps.shape}")
print(f"Array data type: {temps.dtype}")

# 2D array (multiple sensors)
sensors = np.array([
    [85.2, 2100, 3.2],  # Engine 1: temp, pressure, vibration
    [86.1, 2110, 3.3],  # Engine 2
    [87.3, 2120, 3.5],  # Engine 3
    [90.1, 2250, 4.2]   # Engine 4 (getting worse!)
])
print(f"\nMulti-sensor array shape: {sensors.shape}")
print(f"(4 engines, 3 sensors each)\n{sensors}")

# ===== 2. INDEXING (Get specific values) =====
print("\n2. INDEXING & SLICING")

print(f"First temperature: {temps[0]}")
print(f"Last temperature: {temps[-1]}")
print(f"Temperatures 1-4: {temps[1:5]}")

# 2D indexing
print(f"Engine 3 temperature: {sensors[2, 0]}")  # Row 2, Column 0
print(f"All pressures: {sensors[:, 1]}")  # All rows, column 1

# ===== 3. MATH OPERATIONS =====
print("\n3. MATHEMATICAL OPERATIONS")

print(f"Average temperature: {np.mean(temps):.2f}°C")
print(f"Max temperature: {np.max(temps):.2f}°C")
print(f"Min temperature: {np.min(temps):.2f}°C")
print(f"Std deviation: {np.std(temps):.2f}°C (variation in readings)")

# Calculate rate of change (degradation speed)
temp_diff = np.diff(temps)  # Difference between consecutive readings
print(f"Temperature changes: {temp_diff}")
print(f"Average temp increase: {np.mean(temp_diff):.2f}°C per reading")

# ===== 4. FILTERING (Find problem equipment) =====
print("\n4. FILTERING DATA (Find equipment over threshold)")

# Which temperatures are dangerously high (>89°C)?
dangerous_temps = temps[temps > 89]
print(f"Dangerous temps (>89°C): {dangerous_temps}")

# Which engines have high temperature AND high vibration?
problem_engines = sensors[(sensors[:, 0] > 88) & (sensors[:, 2] > 3.5)]
print(f"Problem engines (temp>88 AND vibration>3.5):")
print(problem_engines)

# ===== 5. STATISTICS FOR PREDICTIVE MAINTENANCE =====
print("\n5. STATISTICS FOR YOUR DOMAIN")

print("\nAnalyzing sensor data:")
print(f"  Temperature - Mean: {np.mean(sensors[:, 0]):.1f}°C")
print(f"  Temperature - Std:  {np.std(sensors[:, 0]):.1f}°C (consistency)")
print(f"  Pressure    - Mean: {np.mean(sensors[:, 1]):.0f} psi")
print(f"  Vibration   - Mean: {np.mean(sensors[:, 2]):.2f}G")

print("\n" + "="*50)
print("WHAT THIS MEANS FOR PREDICTIVE MAINTENANCE:")
print("="*50)
print("""
NumPy lets you:
✓ Store sensor readings efficiently (arrays)
✓ Calculate statistics quickly (mean, std, max, min)
✓ Filter problem equipment automatically (temp > threshold)
✓ Compare sensors across engines
✓ Identify degradation patterns (rate of change)

Your mechanical knowledge + NumPy skills =
Can identify which equipment will fail BEFORE it fails.
""")

NUMPY: FOUNDATION FOR ML ENGINEERS

1. CREATING ARRAYS
Temperature array: [85.2 86.1 87.3 88.5 89.2 90.1 91.3]
Array shape (how many readings): (7,)
Array data type: float64

Multi-sensor array shape: (4, 3)
(4 engines, 3 sensors each)
[[  85.2 2100.     3.2]
 [  86.1 2110.     3.3]
 [  87.3 2120.     3.5]
 [  90.1 2250.     4.2]]

2. INDEXING & SLICING
First temperature: 85.2
Last temperature: 91.3
Temperatures 1-4: [86.1 87.3 88.5 89.2]
Engine 3 temperature: 87.3
All pressures: [2100. 2110. 2120. 2250.]

3. MATHEMATICAL OPERATIONS
Average temperature: 88.24°C
Max temperature: 91.30°C
Min temperature: 85.20°C
Std deviation: 2.02°C (variation in readings)
Temperature changes: [0.9 1.2 1.2 0.7 0.9 1.2]
Average temp increase: 1.02°C per reading

4. FILTERING DATA (Find equipment over threshold)
Dangerous temps (>89°C): [89.2 90.1 91.3]
Problem engines (temp>88 AND vibration>3.5):
[[  90.1 2250.     4.2]]

5. STATISTICS FOR YOUR DOMAIN

Analyzing sensor data:
  Temperature - Mean: 87.2°C
